### ISSUE TITLE
Code changes are reviewed and accepted by peers via Pull Request

### ISSUE THREAD

**Issue by dingjimmy** [dingjimmy/Timesheets#6]
## Acceptance Criteria
- Code changes can only be integrated into the `main` branch via a pull-request
- Pull requests changes MUST build successfully and pass unit/integration tests, before merging into `main`
- Pull requests changes MUST be peer reviewed before being integrated, before merging into `main`

## Tasks
- [x] Setup branch protection rules for `main` branch
- [x] Test push to main fails
- [x] Test PR blocked if build or tests fail

 ❌ ~Test PR blocked if not peer reviewed~
